# Use the audio microcode region as stored in the ROM.
# IMEM start address 0x04001080, size 0xE20, at ROM offset 0xCAAC0.
text_offset = 0xE7740
text_size = 0x0820
text_address = 0x04001080
rom_file_path = "m64.us.z64"
output_file_path = "rsp/aspMain.cpp"
output_function_name = "aspMain"

extra_indirect_branch_targets = []
