// Temporary stub for JPEG RSP microcode until generated by RSPRecomp.
#include "librecomp/rsp.hpp"

RspExitReason njpgdspMain(uint8_t* /*rdram*/, [[maybe_unused]] uint32_t /*ucode_addr*/) {
    // JPEG microcode not implemented yet on this build. Return Unsupported so the caller can handle it.
    return RspExitReason::Unsupported;
}
